name: "NoneFlow"
description: "Manage publish related issues in nonebot2 project"
author: "hemengyang <hmy0119@gmail.com>"
inputs:
  config:
    description: "JSON with settings as described in the README"
    required: true
runs:
  using: "docker"
  image: "docker/noneflow.dockerfile"
branding:
  icon: "box"
  color: "orange"
