name: 'NoneBot2 Plugin Issue Bot'
description: 'Manage plugin related issues in nonebot2 project'
author: 'he0119'
inputs:
  token:
    description: 'GitHub Token'
  base:
    required: true
    description: 'The pull request base branch'
  plugin_path:
    required: true
    description: 'Path for plugins.json'
  adapter_path:
    required: true
    description: 'Path for adapters.json'
  bot_path:
    required: true
    description: 'Path for bots.json'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'orange'