name: Plugin Test Container Builder

on:
  push:
    paths:
      - "src/providers/docker_test/**"
  pull_request:
    paths:
      - "src/providers/docker_test/**"
  workflow_dispatch:

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Tags
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/nonebot/nonetest
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Build and Publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/providers/docker_test/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
